---
platform: linux

image_resource:
  type: docker-image
  source: { repository: pcfbosh/minimal }

inputs:
- name: pcf-bosh-ci
- name: p-mysql-deployment
- name: bosh-vars-store 
- name: mysql-vars-store
- name: terraform-state


outputs:
- name: new-mysql-vars-store

run:
  path: penguin-ci/tasks/deploy-mysql.sh
