---
platform: linux

image_resource:
  type: docker-image
  source: { repository: pcfbosh/minimal }

inputs:
- name: penguin-ci
- name: bosh-vars-store 
- name: terraform-state

run:
  path: penguin-ci/tasks/deploy-scs.sh
