---
name: p-scs

releases:
- name: spring-cloud-broker
  url: https://s3-us-west-1.amazonaws.com/p-spring-cloudservices-1.3.3/spring-cloud-broker-1.3.3-build.10.tgz
  sha1: f57e3555887357b3601999fee94b26992344267a
  version: 1.3.3-build.10

stemcells:
- alias: bosh-aws-xen-hvm-hvm-ubuntu-trusty-go_agent
  os: ubuntu-trusty
  version: '3263.21'
instance_groups:
- name: deploy-service-broker
  azs:
  - z1
  instances: 1
  lifecycle: errand
  jobs:
  - name: deploy-service-broker
    release: spring-cloud-broker
    consumes: {}
    provides: {}
  vm_type: t2.small
  vm_extensions:
  - 1GB_ephemeral_disk
  stemcell: bosh-aws-xen-hvm-hvm-ubuntu-trusty-go_agent
  properties:
    domain: ((system_domain))
    app_domains:
    - apps.((system_domain))
    ssl:
      skip_cert_verify: true
    spring_cloud_broker:
      product_name: 
      app_name: 
      app_uri: 
      broker:
        org_name: 
        space_name: 
        user: ((broker_username))
        password: ((broker_password))
        max_instances: 100
      worker:
        client_id: 
        client_secret: ((broker_worker_client_secret))
        user: admin
        password: ((broker_worker_admin_password))
      instances:
        org_name: 
        space_name: 
        instances_user: p-spring-cloud-services
        instances_password: ((broker_instances_password))
      app_push:
        timeout: 180
        memory: 
      broker_dashboard_secret: ((broker_dashboard_secret))
      persistence_store_type: 
      encryption_key: ((broker_encryption_key))
      cf:
        admin_user: push_apps_manager
        admin_password: ((/aws-director-credhub/cf/push_apps_manager_password))
      uaa:
        admin_client_id: admin
        admin_client_secret: ((/aws-director-credhub/cf/uaa_admin_client_secret))
      buildpack: 
      disable_cert_check: false
  update:
    max_in_flight: 1
  networks:
  - name: private
    default:
    - dns
    - gateway

- name: register-service-broker
  azs:
  - z1
  instances: 1
  lifecycle: errand
  jobs:
  - name: register-service-broker
    release: spring-cloud-broker
    consumes: {}
    provides: {}
  vm_type: t2.small
  vm_extensions:
  - 1GB_ephemeral_disk
  stemcell: bosh-aws-xen-hvm-hvm-ubuntu-trusty-go_agent
  properties:
    domain: ((system_domain))
    app_domains:
    - apps.((system_domain))
    ssl:
      skip_cert_verify: true
    spring_cloud_broker:
      product_name: 
      broker:
        org_name: 
        space_name: 
        user: ((broker_username))
        password: ((broker_password))
        plan_names: 
      app_name: 
      app_uri: 
      encryption_key: ((broker_encryption_key))
      cf:
        admin_user: push_apps_manager
        admin_password: ((/aws-director-credhub/cf/push_apps_manager_password))
      uaa:
        admin_client_id: admin
        admin_client_secret: ((/aws-director-credhub/cf/uaa_admin_client_secret))
  update:
    max_in_flight: 1
  networks:
  - name: private
    default:
    - dns
    - gateway

- name: run-smoke-tests
  azs:
  - z1
  instances: 1
  lifecycle: errand
  jobs:
  - name: smoke-tests
    release: spring-cloud-broker
    consumes: {}
    provides: {}
  vm_type: t2.small
  vm_extensions:
  - 1GB_ephemeral_disk
  stemcell: bosh-aws-xen-hvm-hvm-ubuntu-trusty-go_agent
  properties:
    domain: ((system_domain))
    ssl:
      skip_cert_verify: true
    spring_cloud_broker:
      product_name: 
      broker:
        org_name: 
      smoke_test:
        user: push_apps_manager
        password: ((/aws-director-credhub/cf/push_apps_manager_password))
        space: 
      encryption_key: ((broker_encryption_key))
      cf:
        admin_user: push_apps_manager
        admin_password: ((/aws-director-credhub/cf/push_apps_manager_password))
      uaa:
        admin_client_id: admin
        admin_client_secret: ((/aws-director-credhub/cf/uaa_admin_client_secret))
  update:
    max_in_flight: 1
  networks:
  - name: private
    default:
    - dns
    - gateway

- name: destroy-service-broker
  azs:
  - z1
  instances: 1
  lifecycle: errand
  jobs:
  - name: destroy-service-broker
    release: spring-cloud-broker
    consumes: {}
    provides: {}
  vm_type: t2.small
  vm_extensions:
  - 1GB_ephemeral_disk
  stemcell: bosh-aws-xen-hvm-hvm-ubuntu-trusty-go_agent
  properties:
    domain: ((system_domain))
    app_domains:
    - apps.((system_domain))
    ssl:
      skip_cert_verify: true
    spring_cloud_broker:
      product_name: 
      broker:
        org_name: 
        space_name: 
        user: ((broker_username))
        password: ((broker_password))
        plan_names: 
      worker:
        client_id: 
        client_secret: ((worker_client_secret))
      instances:
        org_name: 
        space_name: 
        instances_user: p-spring-cloud-services
      app_name: 
      app_uri: 
      encryption_key: ((broker_encryption_key))
      cf:
        admin_user: push_apps_manager
        admin_password: ((/aws-director-credhub/cf/push_apps_manager_password))
      uaa:
        admin_client_id: admin
        admin_client_secret: ((/aws-director-credhub/cf/uaa_admin_client_secret))
  update:
    max_in_flight: 1
  networks:
  - name: private
    default:
    - dns
    - gateway

update:
  canaries: 1
  canary_watch_time: 30000-300000
  update_watch_time: 30000-300000
  max_in_flight: 1
  max_errors: 2
  serial: true

variables:
- name: broker_username
  type: password
- name: cf_mysql_backup_endpoint_password
  type: password
- name: broker_password
  type: password
- name: broker_worker_client_secret
  type: password
- name: broker_worker_admin_password
  type: password
- name: broker_instances_password
  type: password
- name: broker_dashboard_secret
  type: password
- name: broker_encryption_key
  type: password
- name: mysql_broker_dashboard_client_secret
  type: password
