## This manifest initializes a new BOSH Director on Amazon Web Services with co-located PostgreSQL database, UAA and CredHub.
## 
## Deployment-specific configuration should be done in file 'init-aws-director-config.yml'. This manifest may be modified, but modification is not required. 
##
## To deploy (requires BOSH v2 CLI) - `bosh create-env init-aws-director.yml --vars-store init-aws-director-config.yml`
---
name: &name aws-director-credhub

releases:
- name: bosh
  url: https://bosh.io/d/github.com/cloudfoundry/bosh?v=261.2
  sha1: d4635b4b82b0dc5fd083b83eb7e7405832f6654b
- name: uaa
  url: http://bosh.io/d/github.com/cloudfoundry/uaa-release?v=24
  sha1: d0feb5494153217f3d62b346f426ad2b2f43511a
- name: credhub
  url: https://github.com/pivotal-cf/credhub-release/releases/download/0.5.1/credhub-0.5.1.tgz
  sha1: fcfa37835c813b175defe01d8fae7d57e7ef669c
#- name: bosh-aws-cpi
#  url: https://bosh.io/d/github.com/cloudfoundry-incubator/bosh-aws-cpi-release?v=56
#  sha1: 2b85e1bdc31f41a26b454f4731bf2d1df2ea17de
- name: bosh-aws-cpi    
  version: 60
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/bosh-aws-cpi-release?v=60
  sha1: 8e40a9ff892204007889037f094a1b0d23777058

resource_pools:
- name: vms
  network: private
  stemcell:
    url: https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-trusty-go_agent?v=3312.7
    sha1: e11da993d8bad4305e4bc51117f1de88a63f76bb
  cloud_properties:
    instance_type: m3.xlarge
    ephemeral_disk: {size: 25000, type: gp2}
    availability_zone: ((az))

disk_pools:
- name: disks
  disk_size: 100000
  cloud_properties: 
    type: gp2

networks:
- name: public
  type: vip
- name: private
  type: manual 
  subnets:
  - range: ((internal_cidr))
    gateway: ((internal_gw))
    #dns: [10.0.0.2]
    cloud_properties: 
      subnet: ((subnet_id))

variables:
- name: tls-ca
  type: certificate
  options: 
    common_name: 'BOSH Director CA'
    is_ca: true
- name: tls
  type: certificate
  options: 
    ca: tls-ca
    common_name: ((external_ip))
    alternative_names: 
    - ((external_ip))
    - ((internal_ip))
    - ((bosh_director_domain))
    - 127.0.0.1
- name: uaa-jwt
  type: rsa 
- name: postgres-admin
  type: password
- name: uaa-users-admin
  type: password
- name: uaa-users-hm
  type: password
- name: uaa-clients-director-to-credhub
  type: password
- name: uaa-admin
  type: password
- name: uaa-login
  type: password
- name: nats
  type: password
- name: blobstore-agent
  type: password
- name: registry-admin
  type: password
- name: blobstore-director
  type: password
- name: mbus
  type: password

jobs:
  - name: *name
    instances: 1
    resource_pool: vms
    persistent_disk_pool: disks
    networks:
      - name: private
        static_ips: 
        - ((internal_ip))
        default:
        - dns
        - gateway
      - name: public 
        static_ips: 
        - ((external_ip))

    templates:
    - name: credhub
      release: credhub
      properties:
        credhub:
          port: 8844
          authentication:
            uaa:
              url: *uaa-url
              verification_key: ((uaa-jwt.public_key))
          data_storage:
            type: postgres
            host: 127.0.0.1
            port: 5432
            username: postgres
            password: ((postgres-admin))
            database: credhub
          tls:
            certificate: ((tls.certificate))
            private_key: ((tls.private_key))
          log_level: info
          encryption:
            keys:
            - provider_name: internal
              #dev_key: ((credhub-encryption-key))
              dev_key: 7DBBD8098CAC7EDC342AE3EA46AD00D7
              active: true
            providers:
            - name: internal
              type: dev_internal
    
    - name: postgres
      release: bosh 
      properties: 
        postgres: &db
          host: 127.0.0.1
          port: 5432
          user: postgres
          password: ((postgres-admin))
          database: bosh
          additional_databases: [uaa, credhub]
          adapter: postgres

    - name: uaa
      release: uaa
      properties:
        uaa:
          url: &uaa-url "https://((external_ip)):8443"
          scim:
            users:
            - name: admin
              password: ((uaa-users-admin))
              groups:
                - scim.write
                - scim.read
                - bosh.admin
                - credhub.read
                - credhub.write
            - name: hm
              password: ((uaa-users-hm))
              groups:
                - bosh.admin
          clients:
            bosh_cli:
              override: true
              authorized-grant-types: password,refresh_token
              scope: openid,bosh.admin,bosh.*.admin
              authorities: uaa.none
              access-token-validity: 120
              refresh-token-validity: 43200
              secret: ""
            credhub_cli:
              override: true
              authorized-grant-types: password,refresh_token
              scope: credhub.read,credhub.write
              authorities: uaa.resource
              access-token-validity: 30
              refresh-token-validity: 3600
              secret: ""
            director_to_credhub:
              override: true
              authorized-grant-types: client_credentials
              scope: uaa.none
              authorities: credhub.read,credhub.write
              access-token-validity: 43200
              secret: ((uaa-clients-director-to-credhub))
          admin: {client_secret: ((uaa-admin))}
          login: {client_secret: ((uaa-login))}
          zones: {internal: {hostnames: []}}
          sslCertificate: ((tls.certificate))
          sslPrivateKey: ((tls.private_key))
          jwt:
            revocable: true
            policy:
              active_key_id: key-1
              keys:
                key-1:
                  signingKey: ((uaa-jwt.private_key))
  
        uaadb:
          address: 127.0.0.1
          port: 5432
          db_scheme: postgresql
          databases:
          - tag: uaa
            name: uaa
          roles:
          - tag: admin
            name: postgres
            password: ((postgres-admin))

        login:
          saml:
            serviceProviderCertificate: ((tls.certificate))
            serviceProviderKey: ((tls.private_key))
            serviceProviderKeyPassword: ""

    - name: director
      release: bosh
      properties:
        director: &director
          address: ((external_ip))
          name: *name
          config_server:
            enabled: true
            url: "https://127.0.0.1:8844/api/"
            ca_cert: ((tls.ca))
            uaa:
              url: *uaa-url
              client_id: director_to_credhub
              client_secret: ((uaa-clients-director-to-credhub))
              ca_cert: ((tls.ca))
          db: *db
          cpi_job: aws_cpi
          max_threads: 10
          enable_snapshots: false
          user_management:
            provider: uaa
            uaa:
              url: *uaa-url
              public_key: ((uaa-jwt.public_key))
          ssl:
            cert: ((tls.certificate))
            key: ((tls.private_key))
          trusted_certs: ((tls.ca))
        agent: &agent
          mbus: nats://nats:((nats))@((internal_ip)):4222
          ntp: *ntp
          blobstore:
             options:
               endpoint: http://((internal_ip)):25250
               user: agent
               password: ((blobstore-agent))
        ntp: *ntp
        nats: *nats
        blobstore: *blobstore

    - name: registry
      release: bosh
      properties:
        registry: &registry
          address: ((internal_ip))
          host: ((internal_ip))
          db: *db
          http: {user: admin, password: ((registry-admin)), port: 25777}
          username: admin
          password: ((registry-admin))
          port: 25777

    - name: nats
      release: bosh
      properties:
        nats: &nats
          address: 127.0.0.1
          user: nats
          password: ((nats))

    - name: blobstore
      release: bosh
      properties:
        blobstore: &blobstore
          address: ((internal_ip))
          port: 25250
          provider: dav
          director:
            user: director
            password: ((blobstore-director))
          agent:
            user: agent
            password: ((blobstore-agent))

    - name: powerdns
      release: bosh
      properties:
        dns:
          address: ((internal_ip))
          domain_name: cf.internal 
          db: *db

    - name: health_monitor
      release: bosh
      properties:
        hm:
          director_account:
            user: hm
            password: ((uaa-users-hm))
            ca_cert: ((tls.ca))
          resurrector_enabled: true
        director: *director
        nats: *nats

    - name: aws_cpi
      release: bosh-aws-cpi
      properties:
        aws: &aws
          access_key_id: ((access_key_id))
          secret_access_key: ((secret_access_key))
          default_key_name: ((default_key_name))
          default_security_groups:
          #- ((default_security_groups))
          #- ((bosh_director_security_groups))
          - bosh_security_group
          region: ((region))
        ntp: &ntp
        - 0.pool.ntp.org
        - 1.pool.ntp.org
        registry: *registry
        blobstore: *blobstore
        nats: *nats
        agent: *agent

cloud_provider:
  template:
    name: aws_cpi
    release: bosh-aws-cpi

  ssh_tunnel:
    host: ((external_ip))
    port: 22
    #user: ((ssh-username))
    user: vcap
    private_key: ((private_key))

  mbus: https://mbus:((mbus))@((external_ip)):6868

  properties:
    aws: *aws
    agent: {mbus: "https://mbus:((mbus))@0.0.0.0:6868"}
    blobstore: {provider: local, path: /var/vcap/micro_bosh/data/cache}
    ntp: *ntp

