---
name: cf-rabbitmq
releases:
- name: cf-rabbitmq
  url: https://s3-us-west-1.amazonaws.com/p-rabbitmq-1.7.14/cf-rabbitmq-222.15.0.tgz
  sha1: ddd29a4cdc59f1dd9da3ca0f833ee867f1cc63a3
  version: '222.15.0'
- name: service-metrics
  url: https://s3-us-west-1.amazonaws.com/p-rabbitmq-1.7.14/service-metrics-1.5.5.tgz
  sha1: b09bd233f3517b9e75d656eeefeec3572f0d39dc
  version: '1.5.5'
- name: loggregator
  url: https://s3-us-west-1.amazonaws.com/p-rabbitmq-1.7.14/loggregator-65.tgz
  sha1: 3526f5ca58c2101e44d6c0cbb3d490b2196ec58f
  version: '65'
- name: rabbitmq-metrics
  url: https://s3-us-west-1.amazonaws.com/p-rabbitmq-1.7.14/rabbitmq-metrics-1.54.0-dev.2.tgz
  sha1: b0c7d729fab13e292d50afeab40d4d178d8f8a43
  version: '1.54.0-dev.2'

stemcells:
- alias: bosh-aws-xen-hvm-hvm-ubuntu-trusty-go_agent
  os: ubuntu-trusty
  version: '3312.18'
instance_groups:
- name: rabbitmq-server
  azs:
  - z1
  - z2
  instances: 2
  lifecycle: service
  jobs:
  - name: rabbitmq-server
    release: cf-rabbitmq
    consumes: {}
    provides: {}
  - name: metron_agent
    release: loggregator
    consumes: {}
    provides: {}
  - name: service-metrics
    release: service-metrics
    consumes: {}
    provides: {}
  - name: rabbitmq-server-metrics
    release: rabbitmq-metrics
    consumes: {}
    provides: {}
  vm_type: m3.large
  vm_extensions:
  - 100GB_ephemeral_disk
  stemcell: bosh-aws-xen-hvm-hvm-ubuntu-trusty-go_agent
  properties:
    metron_agent:
      deployment: cf-rabbitmq
    metron_endpoint:
      shared_secret: ((/aws-director-credhub/cf/dropsonde_shared_secret))
    loggregator:
      etcd:
        machines:
        - 10.0.4.192
    loggregator_endpoint:
      shared_secret: ((/aws-director-credhub/cf/dropsonde_shared_secret))
    service_metrics:
      execution_interval_seconds: 30
      origin: p-rabbitmq
      metrics_command: "/var/vcap/packages/rabbitmq-server-metrics/bin/rabbitmq-server-metrics"
      metrics_command_args:
      - "-erlangBinPath=/var/vcap/packages/erlang/bin/"
      - "-rabbitmqCtlPath=/var/vcap/packages/rabbitmq-server/bin/rabbitmqctl"
      - "-logPath=/var/vcap/sys/log/service-metrics/rabbitmq-server-metrics.log"
      - "-rabbitmqUsername=admin"
      - "-rabbitmqPassword=password"
      - "-rabbitmqApiEndpoint=http://127.0.0.1:15672"
    syslog_aggregator:
      address: 
      port: 
    rabbitmq-server:
      networks:
        apps: private
      static_ips:
      - 10.0.4.193
      - 10.0.5.192
      administrators:
        management:
          username: admin
          password: password
        broker:
          username: broker
          password: ((broker_password))
      plugins:
      - rabbitmq_management
      ssl:
        security_options: 
        key: 
        cert: 
        cacert: 
        verify: false
        verification_depth: 5
        fail_if_no_peer_cert: false
      config: 
      cookie: 
      cluster_partition_handling: pause_minority

  update:
    serial: false
    max_in_flight: 1
  networks:
  - name: private
    default:
    - dns
    - gateway
    static_ips:
    - 10.0.4.193
    - 10.0.5.192

- name: rabbitmq-haproxy
  azs:
  - z2
  instances: 1
  lifecycle: service
  jobs:
  - name: rabbitmq-haproxy
    release: cf-rabbitmq
    consumes: {}
    provides: {}
  - name: metron_agent
    release: loggregator
    consumes: {}
    provides: {}
  - name: service-metrics
    release: service-metrics
    consumes: {}
    provides: {}
  - name: rabbitmq-haproxy-metrics
    release: rabbitmq-metrics
    consumes: {}
    provides: {}
  vm_type: t2.small
  stemcell: bosh-aws-xen-hvm-hvm-ubuntu-trusty-go_agent
  properties:
    metron_agent:
      deployment: cf-rabbitmq
    metron_endpoint:
      shared_secret: ((/aws-director-credhub/cf/dropsonde_shared_secret))
    loggregator:
      etcd:
        machines:
        - 10.0.4.192
    loggregator_endpoint:
      shared_secret: ((/aws-director-credhub/cf/dropsonde_shared_secret))
    service_metrics:
      execution_interval_seconds: 30
      origin: p-rabbitmq
      metrics_command: "/var/vcap/packages/rabbitmq-haproxy-metrics/bin/rabbitmq-haproxy-metrics"
      metrics_command_args:
      - "-haproxyNetwork=unix"
      - "-haproxyAddress=/var/vcap/sys/run/rabbitmq-haproxy/haproxy.sock"
      - "-logPath=/var/vcap/sys/log/service-metrics/rabbitmq-haproxy-metrics.log"
    syslog_aggregator:
      address: 
      port: 
    rabbitmq-haproxy:
      stats:
        username: admin
        password: ((proxy_stats_password))
      networks:
        apps: private
      server_ips:
      - 10.0.4.193
      - 10.0.5.192
      ports: 15672, 5672, 5671, 1883, 8883, 61613, 61614, 15674

  update:
    serial: false
    max_in_flight: 1
  networks:
  - name: private
    default:
    - dns
    - gateway
    static_ips:
    - 10.0.5.193

- name: rabbitmq-broker
  azs:
  - z2
  instances: 1
  lifecycle: service
  jobs:
  - name: rabbitmq-broker
    release: cf-rabbitmq
    consumes: {}
    provides: {}
  - name: metron_agent
    release: loggregator
    consumes: {}
    provides: {}
  - name: service-metrics
    release: service-metrics
    consumes: {}
    provides: {}
  - name: rabbitmq-broker-metrics
    release: rabbitmq-metrics
    consumes: {}
    provides: {}
  vm_type: t2.small
  stemcell: bosh-aws-xen-hvm-hvm-ubuntu-trusty-go_agent
  properties:
    metron_agent:
      deployment: cf-rabbitmq
    metron_endpoint:
      shared_secret: ((/aws-director-credhub/cf/dropsonde_shared_secret))
    loggregator:
      etcd:
        machines:
        - 10.0.4.192
    loggregator_endpoint:
      shared_secret: ((/aws-director-credhub/cf/dropsonde_shared_secret))
    service_metrics:
      execution_interval_seconds: 30
      origin: p-rabbitmq
      metrics_command: "/var/vcap/packages/rabbitmq-broker-metrics/heartbeat.sh"
      metrics_command_args:
      - admin
      - ((rabbitmq_admin_password))
    syslog_aggregator:
      address: 
      port: 
    rabbitmq-broker:
      route: pivotal-rabbitmq-broker
      ip: 10.0.5.194
      networks:
        apps: private
      cc_endpoint: https://api.((system_domain))
      cc_api_version: v2
      uaa_endpoint: https://uaa.((system_domain))
      uaa_client:
        client_id: cf
        username: push_apps_manager
        password: ((/aws-director-credhub/cf/push_apps_manager_password))
      rabbitmq:
        operator_set_policy:
          enabled: false
          policy_name: operator_set_policy
          policy_definition: |
            {"ha-mode": "exactly", "ha-params": 2, "ha-sync-mode": "automatic"}
          policy_priority: 50
        management_domain: pivotal-rabbitmq.((system_domain))
        management_ip: 10.0.5.193
        hosts:
        - 10.0.5.193
        dns_host: 
        administrator:
          username: broker
          password: ((broker_password))
        ssl: 
      service:
        url: 10.0.5.194
        username: admin
        password: ((rabbitmq_admin_password))
      logging:
        level: info
        print_stack_traces: true
    cf:
      domain: ((system_domain))
      nats:
        host: 10.0.4.191
        port: 4222
        username: nats
        password: ((/aws-director-credhub/cf/nats_password))

  update:
    serial: false
    max_in_flight: 1
  networks:
  - name: private
    default:
    - dns
    - gateway
    static_ips:
    - 10.0.5.194

- name: broker-registrar
  azs:
  - z1
  instances: 1
  lifecycle: errand
  jobs:
  - name: broker-registrar
    release: cf-rabbitmq
    consumes: {}
    provides: {}
  vm_type: t2.small
  stemcell: bosh-aws-xen-hvm-hvm-ubuntu-trusty-go_agent
  properties:
    broker:
      name: p-rabbitmq
      host: pivotal-rabbitmq-broker.((system_domain))
      username: admin
      password: ((rabbitmq_admin_password))
    cf:
      api_url: https://api.((system_domain))
      admin_username: push_apps_manager
      admin_password: ((/aws-director-credhub/cf/push_apps_manager_password))
      skip_ssl_validation: false
  
  update:
    max_in_flight: 1
  networks:
  - name: private
    default:
    - dns
    - gateway
- name: broker-deregistrar
  azs:
  - z1
  instances: 1
  lifecycle: errand
  jobs:
  - name: broker-deregistrar
    release: cf-rabbitmq
    consumes: {}
    provides: {}
  vm_type: t2.small
  stemcell: bosh-aws-xen-hvm-hvm-ubuntu-trusty-go_agent
  properties:
    broker:
      name: p-rabbitmq
      host: pivotal-rabbitmq-broker.((system_domain))
      username: admin
      password: ((rabbitmq_admin_password))
    cf:
      api_url: https://api.((system_domain))
      admin_username: push_apps_manager
      admin_password: ((/aws-director-credhub/cf/push_apps_manager_password))
      skip_ssl_validation: false
  
  update:
    max_in_flight: 1
  networks:
  - name: private
    default:
    - dns
    - gateway
update:
  canaries: 1
  canary_watch_time: 30000-300000
  update_watch_time: 30000-300000
  max_in_flight: 1
  max_errors: 2
  serial: true

variables:
- name: broker_password
  type: password
- name: proxy_stats_password
  type: password
- name: rabbitmq_admin_password
  type: password
