
---
name: p-rabbitmq
releases:
- name: cf-rabbitmq
  url: https://s3-us-west-1.amazonaws.com/p-rabbitmq-1.7.5/cf-rabbitmq-222.6.0.tgz
  sha1: e5dc49bfb1dc1d0239698a2886c1d155fd18eb6b
  version: 222.6.0
- name: service-metrics
  url: https://s3-us-west-1.amazonaws.com/p-rabbitmq-1.7.5/service-metrics-1.4.3.tgz
  sha1: 6e35ca4656868a628bb4c9c9ebd33e7b8d962835
  version: 1.4.3
- name: loggregator
  url: https://s3-us-west-1.amazonaws.com/p-rabbitmq-1.7.5/loggregator-65.tgz
  sha1: 3526f5ca58c2101e44d6c0cbb3d490b2196ec58f
  version: '65'
- name: rabbitmq-metrics
  url: https://s3-us-west-1.amazonaws.com/p-rabbitmq-1.7.5/rabbitmq-metrics-1.29.0.tgz
  sha1: fba3446cb7ee46358b80be9f2df9febe9d8b8300
  version: 1.29.0

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: rabbitmq-server
  azs:
  - z1
  instances: 1
  lifecycle: service
  jobs:
  - name: rabbitmq-server
    release: cf-rabbitmq
    consumes: {}
    provides: {}
  vm_type: r3.large
  stemcell: default
  vm_extensions:
  - 5GB_ephemeral_disk
  properties:
    rabbitmq-server:
      networks:
        apps: default
      static_ips:
      - 10.0.31.192 # {RABBITMQ_SERVER_IP}
      administrators:
        management:
          username: admin
          password: ((broker_password))
        broker:
          username: broker
          password: "((broker_password))"
      plugins:
      - rabbitmq_management
      ssl:
        security_options: 
        key: 
        cert: 
        cacert: 
        verify: false
        verification_depth: 5
        fail_if_no_peer_cert: false
      config: 
      cookie: 
      cluster_partition_handling: pause_minority
  update:
    serial: false
    max_in_flight: 1
  networks:
  - name: private
    default:
    - dns
    - gateway
    static_ips:
    - 10.0.31.192 # {RABBITMQ_SERVER_IP}
  persistent_disk_type: '10GB' # {PERSISTENT_DISK_TYPE}

- name: rabbitmq-haproxy
  azs:
  - z1
  instances: 1
  lifecycle: service
  jobs:
  - name: rabbitmq-haproxy
    release: cf-rabbitmq
    consumes: {}
    provides: {}
  #- name: metron_agent
  #  release: loggregator
  #  consumes: {}
  #  provides: {}
  #- name: service-metrics
  #  release: service-metrics
  #  consumes: {}
  #  provides: {}
  #- name: rabbitmq-haproxy-metrics
  #  release: rabbitmq-metrics
  #  consumes: {}
  #  provides: {}
  vm_type: m3.medium
  vm_extensions:
  - 5GB_ephemeral_disk
  persistent_disk_type: '10GB'
  stemcell: default
  properties:
    rabbitmq-haproxy:
      stats:
        username: admin
        password: ((broker_password))
      networks:
        apps: default
      server_ips:
      - 10.0.31.192 # {RABBITMQ_SERVER_IP}
      ports: 15672, 5672, 5671, 1883, 8883, 61613, 61614, 15674
  update:
    serial: false
    max_in_flight: 1
  networks:
  - name: private
    default:
    - dns
    - gateway
    static_ips:
    - 10.0.31.195 # {RABBITMQ_PROXY_IP}

- name: rabbitmq-broker
  azs:
  - z1
  instances: 1
  lifecycle: service
  jobs:
  - name: rabbitmq-broker
    release: cf-rabbitmq
    consumes: {}
    provides: {}
  vm_type: m3.medium
  vm_extensions:
  - 5GB_ephemeral_disk
  persistent_disk_type: '10GB'
  stemcell: default
  properties:
    rabbitmq-broker:
      route: pivotal-rabbitmq-broker
      ip: 10.0.31.194  # {RABBITMQ_BROKER_IP}
      networks:
        apps: default
      cc_endpoint: https://api.((system_domain))
      cc_api_version: v2
      uaa_endpoint: https://uaa.((system_domain))
      uaa_client:
        client_id: cf
        username: admin
        password: "((system_services_password))" # {SYSTEM_SERVICES_PASSWORD}
      rabbitmq:
        operator_set_policy:
          enabled: false
          policy_name: operator_set_policy
          policy_definition: |
            {"ha-mode": "exactly", "ha-params": 2, "ha-sync-mode": "automatic"}
          policy_priority: 50
        management_domain: pivotal-rabbitmq.((system_domain))
        management_ip: 10.0.31.195 # {RABBITMQ_PROXY_IP}
        hosts:
        - 10.0.31.195 # {RABBITMQ_PROXY_IP}
        dns_host: 
        administrator:
          username: broker
          password: ((broker_password))
        ssl: 
      service:
        url: 10.0.31.194 # {RABBITMQ_BROKER_IP}
        username: admin
        password: "((service_broker_password))"
      logging:
        level: info
        print_stack_traces: true
    cf:
      domain: "((system_domain))"
      nats:
        host: 10.0.31.191
        port: 4222
        username: nats
        password: "((nats_password))"
  update:
    serial: false
    max_in_flight: 1
  networks:
  - name: private
    default:
    - dns
    - gateway
    static_ips:
    - 10.0.31.194 # {RABBITMQ_BROKER_IP}

- name: broker-registrar
  azs:
  - z1
  instances: 1
  lifecycle: errand
  jobs:
  - name: broker-registrar
    release: cf-rabbitmq
    consumes: {}
    provides: {}
  vm_type: m3.medium
  vm_extensions:
  - 5GB_ephemeral_disk
  stemcell: default
  properties:
    broker:
      name: p-rabbitmq
      host: pivotal-rabbitmq-broker.((system_domain))
      username: admin
      password: "((service_broker_password))"
    cf:
      api_url: https://api.((system_domain))
      admin_username: admin
      admin_password: "((system_services_password))"  # {SYSTEM_SERVICES_PASSWORD}
      skip_ssl_validation: true
  update:
    max_in_flight: 1
  networks:
  - name: private
    default:
    - dns
    - gateway

- name: broker-deregistrar
  azs:
  - z1
  instances: 1
  lifecycle: errand
  jobs:
  - name: broker-deregistrar
    release: cf-rabbitmq
    consumes: {}
    provides: {}
  vm_type: m3.medium
  vm_extensions:
  - 5GB_ephemeral_disk
  stemcell: default
  properties:
    broker:
      name: p-rabbitmq
      host: pivotal-rabbitmq-broker.((system_domain))
      username: admin
      password: "((service_broker_password))" 
    cf:
      api_url: https://api.((system_domain))
      admin_username: admin
      admin_password: "((system_services_password))" # {SYSTEM_SERVICES_PASSWORD}
      skip_ssl_validation: true
  update:
    max_in_flight: 1
  networks:
  - name: private
    default:
    - dns
    - gateway
update:
  canaries: 1
  canary_watch_time: 30000-300000
  update_watch_time: 30000-300000
  max_in_flight: 1
  max_errors: 2
  serial: true

variables:
- name: broker_password
  type: password
- name: service_broker_password
  type: password
  